blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussion
    url: https://github.com/OWNER/REPO/discussions
    about: Ask questions and share ideas with the community
  - name: ðŸ“š Documentation
    url: https://github.com/OWNER/REPO/wiki
    about: Read the documentation and wiki







