blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussion
    url: https://github.com/OWNER/REPO/discussions
    about: Vraag vragen en deel ideeÃ«n met de community
  - name: ðŸ“š Documentation
    url: https://github.com/OWNER/REPO/wiki
    about: Bekijk de documentatie en wiki



