global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'traefik-monitor'

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
